org: chrsbell
app: anime-connect-native
service: services
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-webpack

custom:
  webpack:
    config: webpack.config.js
    series: false # run Webpack in series, useful for large projects. Defaults to false.
