org: chrsbell
app: anime-connect-native
service: user
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: functions/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    lambdaPort: 3003
